name: Build Android

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - rust_target: aarch64-linux-android
            artifact_prefix: android-aarch64
          - rust_target: armv7-linux-androideabi
            artifact_prefix: android-armv7
          - rust_target: i686-linux-android
            artifact_prefix: android-i686
          - rust_target: x86_64-linux-android
            artifact_prefix: android-x86_64

    steps:
      - uses: actions/checkout@v7

      - name: Setup JDK 17
        uses: actions/setup-java@v5.4.0
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK/NDK
        uses: android-actions/setup-android@v4.0.1
        with:
          packages: |
            platforms;android-24
            build-tools;34.0.0
            platform-tools
            ndk;27.3.13750724

      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.rust_target }}

      - name: Cache Rust
        uses: actions/cache@v6.1.0
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            src/src-tauri/target
          key: ${{ runner.os }}-cargo-${{ matrix.rust_target }}-${{ hashFiles('src/src-tauri/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-${{ matrix.rust_target }}-

      - run: bun install --frozen-lockfile

      - name: Android signature
        run: |
          cd src-tauri/gen/android
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > keystore.properties
          echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
          base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

      - name: Build Tauri Android
        run: bun tauri android build -- --target ${{ matrix.rust_target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.artifact_prefix }}
          path: release/*